### ISSUE TITLE
letter issue 

### ISSUE THREAD

**Issue by Danielanyok** [WebDevSimplified/wordle-clone#10]

**Comment by alexmangini** [comment]
Amazing script! This has been the only issue I've encountered using it as well. If I find a fix I will post it here.

**Comment by sean-b765** [comment]
I made my own wordle clone in Vue.js using an animation library. 
I got around this issue by keeping track of the appearances of each letter

Take a look at my checkWord function
```ts

checkWord(guessedWord: string) {
  // The indices in this dictionary correspond to the status of each letter being "correct" or "close"
  //  e.g. for the word "apple", with a guess of "opens"
  // { 1: "", 2: "correct", 3: "in-word", 4: "", 5: "" }
  const indices: {
    [key: number]: string
  } = {1: "", 2: "", 3: "", 4: "", 5: ""}

  // Keep a string of the matching characters so we can keep track of the prior appearances while iterating
  let matchingChars = ''

  for (let i = 0; i < this.word.length; i++) {
    const letter = guessedWord[i]

    const rgx = new RegExp(`${letter}`, "g")
    // Need to know the total appearances of the letter in the word
    const totalAppearances = (this.word.match(rgx) || []).length
    // Also need to know all prior appearances of the letter in the word, 
    //  so we don't mistakenly tell the user that a duplicate letter exists
    const priorAppearances = (matchingChars.match(rgx) || []).length

    if (!this.word.includes(letter)) {
      this.guessedLetters.push(letter)
      // can continue the loop without checking correctness of the letter
      continue
    }

    // The letter is correct
    if (this.word[i] === guessedWord[i]) {
      indices[i + 1] = "correct"

      if (!this.correctLetters.includes(letter)) {
        this.correctLetters.push(letter)
      }

      matchingChars = matchingChars + letter
      continue
    }

    // The letter is included in the word

    // Look ahead... If there is a correct appearance further in the word, we need to know
    let futureCorrectAppearances = 0
    for (let j = i; j < this.word.length; j++) {
      if (this.word[j] === guessedWord[j] && this.word[j] === letter) futureCorrectAppearances++
    }

    // There are correct appearances further ahead in the word, so we should continue
    if (futureCorrectAppearances >= totalAppearances) continue

    // Ensure duplicates are accounted for
    if (priorAppearances >= totalAppearances) continue

    //  the letter is in word
    if (!this.closeLetters.includes(letter)) this.closeLetters.push(letter)

    indices[i + 1] = "in-word"

    matchingChars = matchingChars + letter
  }// end for

  // win event
  if (this.word === guessedWord) return { win: true, indices }

  return { indices, win: false }
}

```

**Comment by cyberabi** [comment]
The current code in master still doesn't properly resolve a case where the player enters more of a given letter than there are in the word. For example, guessing "EERIE" when the word is "QUEER." Here's my fix for it:

```
...
  stopInteraction()
  flips = mapTiles(guess)
  activeTiles.forEach((...params) => flipTile(...params, guess, flips))
}

function mapTiles(guess) {

  // Pass 1: Number of times each letter occurs in target word
  var targetMap = [...targetWord].reduce((res, char) => (res[char] = (res[char] || 0) + 1, res), {})

  // Pass 2: All of the correct guesses (and build five letter map)
  var map2 = ""
  for (var i = 0; i < guess.length; i++) {
    var c = guess.charAt(i)
    if (c === targetWord.charAt(i)) {
      map2 += "c"
      targetMap[c] -= 1
    } else {
      map2 += "i"
    }
  }

  // Pass 3: Letters in the word, but in incorrect positions
  var map3 = ""
  for (var i = 0; i < map2.length; i++) {
    var f = map2.charAt(i)
    if (f === 'i') {
      var c = guess.charAt(i)
      if (targetMap.hasOwnProperty(c) && (targetMap[c] > 0)) {
        targetMap[c] -= 1
        f = 'p'
      }
    }
    map3 += f
  }

  return map3
}

function flipTile(tile, index, array, guess, flips) {
  const letter = tile.dataset.letter
  const key = keyboard.querySelector(`[data-key="${letter}"i]`)
  const status = flips.charAt(index)

  setTimeout(() => {
    tile.classList.add("flip")
  }, (index * FLIP_ANIMATION_DURATION) / 2)

  tile.addEventListener(
    "transitionend",
    () => {
      tile.classList.remove("flip")
      if (status === 'c') {
        tile.dataset.state = "correct"
        key.classList.add("correct")
      } else if (status === 'p') {
        tile.dataset.state = "wrong-location"
        key.classList.add("wrong-location")
      } else {
        tile.dataset.state = "wrong"
        key.classList.add("wrong")
      }
...
```

**Comment by GuilhermeAFCruz** [comment]
> The current code in master still doesn't properly resolve a case where the player enters more of a given letter than there are in the word. For example, guessing "EERIE" when the word is "QUEER." Here's my fix for it:
> 
> ```
> ...
>   stopInteraction()
>   flips = mapTiles(guess)
>   activeTiles.forEach((...params) => flipTile(...params, guess, flips))
> }
> 
> function mapTiles(guess) {
> 
>   // Pass 1: Number of times each letter occurs in target word
>   var targetMap = [...targetWord].reduce((res, char) => (res[char] = (res[char] || 0) + 1, res), {})
> 
>   // Pass 2: All of the correct guesses (and build five letter map)
>   var map2 = ""
>   for (var i = 0; i < guess.length; i++) {
>     var c = guess.charAt(i)
>     if (c === targetWord.charAt(i)) {
>       map2 += "c"
>       targetMap[c] -= 1
>     } else {
>       map2 += "i"
>     }
>   }
> 
>   // Pass 3: Letters in the word, but in incorrect positions
>   var map3 = ""
>   for (var i = 0; i < map2.length; i++) {
>     var f = map2.charAt(i)
>     if (f === 'i') {
>       var c = guess.charAt(i)
>       if (targetMap.hasOwnProperty(c) && (targetMap[c] > 0)) {
>         targetMap[c] -= 1
>         f = 'p'
>       }
>     }
>     map3 += f
>   }
> 
>   return map3
> }
> 
> function flipTile(tile, index, array, guess, flips) {
>   const letter = tile.dataset.letter
>   const key = keyboard.querySelector(`[data-key="${letter}"i]`)
>   const status = flips.charAt(index)
> 
>   setTimeout(() => {
>     tile.classList.add("flip")
>   }, (index * FLIP_ANIMATION_DURATION) / 2)
> 
>   tile.addEventListener(
>     "transitionend",
>     () => {
>       tile.classList.remove("flip")
>       if (status === 'c') {
>         tile.dataset.state = "correct"
>         key.classList.add("correct")
>       } else if (status === 'p') {
>         tile.dataset.state = "wrong-location"
>         key.classList.add("wrong-location")
>       } else {
>         tile.dataset.state = "wrong"
>         key.classList.add("wrong")
>       }
> ...
> ```

nice solution, tried other solution before but yours solved another problem i was having, but i couldn't actually undestand the code correctly, can you comment on it or something? i'm kinda new to JS in general.

**Comment by cyberabi** [comment]
Received a request to better describe the change I posted above.

In Pass 1, we use map-reduce functionality built into JavaScript to create an associative array with each unique letter of the correct answer as a key, and the number of times that letter occurs in the word as the value. So for example if the correct answer is QUEER the map is { E:2, Q:1, R:1, U:1 }. This map is called targetMap.

In Pass 2, we do two things at once based on whether each letter of the player's guess is correct or not.

One thing we do in Pass 2 is create a five-letter string consisting of the letters 'i' and 'c'. An 'i' means incorrect, and a 'c' means correct. Every place where the player's guess matches the correct answer gets a 'c' and the others get an 'i'. So for example if the player's guess is SPEAR and the correct answer is QUEER, we produce the five-letter string 'iicic'. This string is called map2.

The other thing we do in Pass 2 is decrement the count in targetMap (that we created in Pass 1) by one for each correct letter guess in the correct position. So for example if the player's guess is SPEAR and the correct answer is QUEER, at the end of Pass 2 the targetMap will be { E:1, Q:1, R:0, U:1 } because one E and one R are correct letters in the correct position. Notice that we didn't delete the 'R' key in targetMap, even though its count is zero.

In Pass 3 we build the map3 string as a copy of map2, but replace 'i' characters with 'p' characters when the letter is correct but in the wrong position ('p' for position). We do this by, for every position in map2 that contains an 'i', looking at the letter in the corresponding position of the player's guess and seeing if targetMap has a non-zero count for that letter. If it does, we replace the 'i' with a 'p' in map3 and decrement the count in targetMap. So for example if the player's guess is SPEAR and the correct answer is QUEER, there are no letters in the player's guess that are correct but in the wrong position, and map3 will be the same as map2. Using targetMap in this way makes sure we properly account for multiples of the same letter in all cases and edge cases. The resulting map3 string tells us what color we should make each tile that we reveal as the result of the player's guess: green for correct position and letter ('c'); yellow for correct letter in the wrong position ('p'); gray for completely incorrect ('i').

We return map3 from mapTiles(), as the flips string. We pass flips down to flipTile(), and modify the rest of the code so that it uses the 'i', 'c' and 'p' characters for each position to determine the tile color.

Hope this helps!
